[2022-07-05 15:28:27,473] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2022-07-05 15:28:27,920] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2022-07-05 15:28:27,937] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 15:28:27,939] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-07-05 15:28:27,943] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 15:28:28,149] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2022-03-02 06:00:00+00:00
[2022-07-05 15:28:28,267] {standard_task_runner.py:52} INFO - Started process 251 to run task
[2022-07-05 15:28:28,506] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'wget', 'scheduled__2022-03-02T06:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpy57or9oe', '--error-file', '/tmp/tmpkm5cr82k']
[2022-07-05 15:28:28,523] {standard_task_runner.py:77} INFO - Job 47: Subtask wget
[2022-07-05 15:28:29,387] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.wget scheduled__2022-03-02T06:00:00+00:00 [running]> on host 730d3c67d882
[2022-07-05 15:28:29,648] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2022-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-02T06:00:00+00:00
[2022-07-05 15:28:29,653] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-05 15:28:29,655] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'ech "hello world"']
[2022-07-05 15:28:29,687] {subprocess.py:85} INFO - Output:
[2022-07-05 15:28:29,698] {subprocess.py:89} INFO - bash: ech: command not found
[2022-07-05 15:28:29,702] {subprocess.py:93} INFO - Command exited with return code 127
[2022-07-05 15:28:29,769] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-05 15:28:29,795] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=wget, execution_date=20220302T060000, start_date=20220705T152827, end_date=20220705T152829
[2022-07-05 15:28:29,878] {standard_task_runner.py:92} ERROR - Failed to execute job 47 for task wget
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-05 15:28:29,936] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 15:28:30,155] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-04 21:02:49,804] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2022-08-04 21:02:49,864] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2022-08-04 21:02:49,865] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-04 21:02:49,866] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-08-04 21:02:49,869] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-04 21:02:49,956] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2022-03-02 06:00:00+00:00
[2022-08-04 21:02:49,972] {standard_task_runner.py:52} INFO - Started process 132 to run task
[2022-08-04 21:02:49,993] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'wget', 'scheduled__2022-03-02T06:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp4istgoff', '--error-file', '/tmp/tmpxx5dutek']
[2022-08-04 21:02:49,997] {standard_task_runner.py:77} INFO - Job 17: Subtask wget
[2022-08-04 21:02:50,196] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.wget scheduled__2022-03-02T06:00:00+00:00 [running]> on host b20bc6ac5db7
[2022-08-04 21:02:50,288] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-08-04 21:02:50,326] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2022-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-02T06:00:00+00:00
[2022-08-04 21:02:50,330] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-04 21:02:50,331] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "2022_03" ']
[2022-08-04 21:02:50,364] {subprocess.py:85} INFO - Output:
[2022-08-04 21:02:50,370] {subprocess.py:89} INFO - 2022_03
[2022-08-04 21:02:50,372] {subprocess.py:93} INFO - Command exited with return code 0
[2022-08-04 21:02:50,414] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=LocalIngestionDag, task_id=wget, execution_date=20220302T060000, start_date=20220804T210249, end_date=20220804T210250
[2022-08-04 21:02:50,493] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-08-04 21:02:50,768] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
