[2022-07-05 15:28:29,482] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2022-04-02T06:00:00+00:00 [queued]>
[2022-07-05 15:28:29,572] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2022-04-02T06:00:00+00:00 [queued]>
[2022-07-05 15:28:29,581] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 15:28:29,586] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-07-05 15:28:29,589] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 15:28:29,667] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2022-04-02 06:00:00+00:00
[2022-07-05 15:28:29,680] {standard_task_runner.py:52} INFO - Started process 253 to run task
[2022-07-05 15:28:29,706] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'wget', 'scheduled__2022-04-02T06:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpt8rilcc9', '--error-file', '/tmp/tmphbi9h67m']
[2022-07-05 15:28:29,717] {standard_task_runner.py:77} INFO - Job 48: Subtask wget
[2022-07-05 15:28:30,055] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.wget scheduled__2022-04-02T06:00:00+00:00 [running]> on host 730d3c67d882
[2022-07-05 15:28:30,304] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2022-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-02T06:00:00+00:00
[2022-07-05 15:28:30,313] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-05 15:28:30,317] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'ech "hello world"']
[2022-07-05 15:28:30,343] {subprocess.py:85} INFO - Output:
[2022-07-05 15:28:30,351] {subprocess.py:89} INFO - bash: ech: command not found
[2022-07-05 15:28:30,352] {subprocess.py:93} INFO - Command exited with return code 127
[2022-07-05 15:28:30,580] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-05 15:28:30,665] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=wget, execution_date=20220402T060000, start_date=20220705T152829, end_date=20220705T152830
[2022-07-05 15:28:30,881] {standard_task_runner.py:92} ERROR - Failed to execute job 48 for task wget
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-05 15:28:30,968] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 15:28:31,137] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-04 21:02:49,742] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2022-04-02T06:00:00+00:00 [queued]>
[2022-08-04 21:02:49,803] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2022-04-02T06:00:00+00:00 [queued]>
[2022-08-04 21:02:49,804] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-04 21:02:49,805] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-08-04 21:02:49,806] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-04 21:02:49,826] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2022-04-02 06:00:00+00:00
[2022-08-04 21:02:49,848] {standard_task_runner.py:52} INFO - Started process 129 to run task
[2022-08-04 21:02:49,909] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'wget', 'scheduled__2022-04-02T06:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpmti__2t1', '--error-file', '/tmp/tmpdu4ccfnr']
[2022-08-04 21:02:49,915] {standard_task_runner.py:77} INFO - Job 16: Subtask wget
[2022-08-04 21:02:50,078] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.wget scheduled__2022-04-02T06:00:00+00:00 [running]> on host b20bc6ac5db7
[2022-08-04 21:02:50,215] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-08-04 21:02:50,271] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2022-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-02T06:00:00+00:00
[2022-08-04 21:02:50,273] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-04 21:02:50,275] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "2022_04" ']
[2022-08-04 21:02:50,308] {subprocess.py:85} INFO - Output:
[2022-08-04 21:02:50,320] {subprocess.py:89} INFO - 2022_04
[2022-08-04 21:02:50,321] {subprocess.py:93} INFO - Command exited with return code 0
[2022-08-04 21:02:50,372] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=LocalIngestionDag, task_id=wget, execution_date=20220402T060000, start_date=20220804T210249, end_date=20220804T210250
[2022-08-04 21:02:50,411] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-08-04 21:02:50,504] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
