[2022-07-05 15:28:33,782] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2022-06-02T06:00:00+00:00 [queued]>
[2022-07-05 15:28:33,809] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2022-06-02T06:00:00+00:00 [queued]>
[2022-07-05 15:28:33,810] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 15:28:33,812] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-07-05 15:28:33,814] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 15:28:33,835] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2022-06-02 06:00:00+00:00
[2022-07-05 15:28:33,853] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'wget', 'scheduled__2022-06-02T06:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpd9riyw9m', '--error-file', '/tmp/tmp5sxoxfku']
[2022-07-05 15:28:33,857] {standard_task_runner.py:77} INFO - Job 50: Subtask wget
[2022-07-05 15:28:33,844] {standard_task_runner.py:52} INFO - Started process 268 to run task
[2022-07-05 15:28:34,214] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.wget scheduled__2022-06-02T06:00:00+00:00 [running]> on host 730d3c67d882
[2022-07-05 15:28:34,475] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2022-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-02T06:00:00+00:00
[2022-07-05 15:28:34,489] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-05 15:28:34,492] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'ech "hello world"']
[2022-07-05 15:28:34,570] {subprocess.py:85} INFO - Output:
[2022-07-05 15:28:34,589] {subprocess.py:89} INFO - bash: ech: command not found
[2022-07-05 15:28:34,592] {subprocess.py:93} INFO - Command exited with return code 127
[2022-07-05 15:28:34,709] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-05 15:28:34,748] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=wget, execution_date=20220602T060000, start_date=20220705T152833, end_date=20220705T152834
[2022-07-05 15:28:34,847] {standard_task_runner.py:92} ERROR - Failed to execute job 50 for task wget
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-05 15:28:34,915] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-05 15:28:35,001] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-04 21:02:51,410] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2022-06-02T06:00:00+00:00 [queued]>
[2022-08-04 21:02:51,426] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget scheduled__2022-06-02T06:00:00+00:00 [queued]>
[2022-08-04 21:02:51,427] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-04 21:02:51,428] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-08-04 21:02:51,429] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-04 21:02:51,471] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2022-06-02 06:00:00+00:00
[2022-08-04 21:02:51,489] {standard_task_runner.py:52} INFO - Started process 145 to run task
[2022-08-04 21:02:51,521] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'wget', 'scheduled__2022-06-02T06:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpxs40ngev', '--error-file', '/tmp/tmp7oswqdvc']
[2022-08-04 21:02:51,524] {standard_task_runner.py:77} INFO - Job 20: Subtask wget
[2022-08-04 21:02:51,731] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.wget scheduled__2022-06-02T06:00:00+00:00 [running]> on host b20bc6ac5db7
[2022-08-04 21:02:51,885] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-08-04 21:02:52,100] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2022-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-02T06:00:00+00:00
[2022-08-04 21:02:52,114] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-04 21:02:52,120] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "2022_06" ']
[2022-08-04 21:02:52,244] {subprocess.py:85} INFO - Output:
[2022-08-04 21:02:52,246] {subprocess.py:89} INFO - 2022_06
[2022-08-04 21:02:52,251] {subprocess.py:93} INFO - Command exited with return code 0
[2022-08-04 21:02:52,487] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=LocalIngestionDag, task_id=wget, execution_date=20220602T060000, start_date=20220804T210251, end_date=20220804T210252
[2022-08-04 21:02:52,882] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-08-04 21:02:53,260] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
