[2022-08-05 17:18:51,635] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: move_gcs_trip_data_to_bq_workflow2.insert_query_job_fhv scheduled__2022-08-04T00:00:00+00:00 [queued]>
[2022-08-05 17:18:51,654] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: move_gcs_trip_data_to_bq_workflow2.insert_query_job_fhv scheduled__2022-08-04T00:00:00+00:00 [queued]>
[2022-08-05 17:18:51,655] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-05 17:18:51,656] {taskinstance.py:1239} INFO - Starting attempt 3 of 4
[2022-08-05 17:18:51,657] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-05 17:18:51,677] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): insert_query_job_fhv> on 2022-08-04 00:00:00+00:00
[2022-08-05 17:18:51,688] {standard_task_runner.py:52} INFO - Started process 7169 to run task
[2022-08-05 17:18:51,693] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'move_gcs_trip_data_to_bq_workflow2', 'insert_query_job_fhv', 'scheduled__2022-08-04T00:00:00+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq.py', '--cfg-path', '/tmp/tmp817j9qel', '--error-file', '/tmp/tmpx0_rx8n6']
[2022-08-05 17:18:51,695] {standard_task_runner.py:77} INFO - Job 118: Subtask insert_query_job_fhv
[2022-08-05 17:18:51,768] {logging_mixin.py:109} INFO - Running <TaskInstance: move_gcs_trip_data_to_bq_workflow2.insert_query_job_fhv scheduled__2022-08-04T00:00:00+00:00 [running]> on host a02ae1da6c7b
[2022-08-05 17:18:51,834] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=move_gcs_trip_data_to_bq_workflow2
AIRFLOW_CTX_TASK_ID=insert_query_job_fhv
AIRFLOW_CTX_EXECUTION_DATE=2022-08-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-04T00:00:00+00:00
[2022-08-05 17:18:51,837] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-08-05 17:18:51,839] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-08-05 17:18:51,848] {bigquery.py:1637} INFO - Inserting job ***_move_gcs_trip_data_to_bq_workflow2_insert_query_job_fhv_2022_08_04T00_00_00_00_00_d4ae63d8893ccc6a1b1c5dc267121459
[2022-08-05 17:18:52,400] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Table wise-logic-354820:trips_data_all.external_fhv_tripdata was not found in location us-east4

(job ID: airflow_move_gcs_trip_data_to_bq_workflow2_insert_query_job_fhv_2022_08_04T00_00_00_00_00_d4ae63d8893ccc6a1b1c5dc267121459)

                          -----Query Job SQL Follows-----                          

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:    
   2:                CREATE OR REPLACE TABLE trips_data_all.fhv_tripdata_partitoned
   3:                PARTITION BY DATE(pickup_datetime) AS
   4:                SELECT * FROM trips_data_all.external_fhv_tripdata;
   5:            
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-08-05 17:18:52,447] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=move_gcs_trip_data_to_bq_workflow2, task_id=insert_query_job_fhv, execution_date=20220804T000000, start_date=20220805T171851, end_date=20220805T171852
[2022-08-05 17:18:52,470] {standard_task_runner.py:92} ERROR - Failed to execute job 118 for task insert_query_job_fhv
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Table wise-logic-354820:trips_data_all.external_fhv_tripdata was not found in location us-east4

(job ID: airflow_move_gcs_trip_data_to_bq_workflow2_insert_query_job_fhv_2022_08_04T00_00_00_00_00_d4ae63d8893ccc6a1b1c5dc267121459)

                          -----Query Job SQL Follows-----                          

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:    
   2:                CREATE OR REPLACE TABLE trips_data_all.fhv_tripdata_partitoned
   3:                PARTITION BY DATE(pickup_datetime) AS
   4:                SELECT * FROM trips_data_all.external_fhv_tripdata;
   5:            
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-08-05 17:18:52,524] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-08-05 17:18:52,568] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
